name: CI to Docker hub 

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          push: true
          tags: singlecellacademy/scap:dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

